.TH Printf 1 "2017-23-10" "Printf man page"
.SH NAME
Printf \- a function that will produce output
.SH DESCRIPTION
This simple functions will produce output depending on what type of operator is used
.SH SYNOPSIS
\#include "holberton.h"
.B Printf

.SH OPTIONS
.IP -o
option for o
.IP -f 
option for f
.TP
.BR \-
.SH SYNOPSIS

.SH AUTHOR
